(cl:in-package com2009_msgs-msg)
(cl:export '(TOTAL_DISTANCE_TRAVELLED-VAL
          TOTAL_DISTANCE_TRAVELLED
          CLOSEST_OBJECT_DISTANCE-VAL
          CLOSEST_OBJECT_DISTANCE
          CLOSEST_OBJECT_ANGLE-VAL
          CLOSEST_OBJECT_ANGLE
))