; Auto-generated. Do not edit!


(cl:in-package com2009_msgs-msg)


;//! \htmlinclude CameraSweepResult.msg.html

(cl:defclass <CameraSweepResult> (roslisp-msg-protocol:ros-message)
  ((image_path
    :reader image_path
    :initarg :image_path
    :type cl:string
    :initform ""))
)

(cl:defclass CameraSweepResult (<CameraSweepResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CameraSweepResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CameraSweepResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name com2009_msgs-msg:<CameraSweepResult> is deprecated: use com2009_msgs-msg:CameraSweepResult instead.")))

(cl:ensure-generic-function 'image_path-val :lambda-list '(m))
(cl:defmethod image_path-val ((m <CameraSweepResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader com2009_msgs-msg:image_path-val is deprecated.  Use com2009_msgs-msg:image_path instead.")
  (image_path m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CameraSweepResult>) ostream)
  "Serializes a message object of type '<CameraSweepResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'image_path))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'image_path))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CameraSweepResult>) istream)
  "Deserializes a message object of type '<CameraSweepResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'image_path) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'image_path) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CameraSweepResult>)))
  "Returns string type for a message object of type '<CameraSweepResult>"
  "com2009_msgs/CameraSweepResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CameraSweepResult)))
  "Returns string type for a message object of type 'CameraSweepResult"
  "com2009_msgs/CameraSweepResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CameraSweepResult>)))
  "Returns md5sum for a message object of type '<CameraSweepResult>"
  "65568c775bfbc96c6265c3d13d7e1a07")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CameraSweepResult)))
  "Returns md5sum for a message object of type 'CameraSweepResult"
  "65568c775bfbc96c6265c3d13d7e1a07")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CameraSweepResult>)))
  "Returns full string definition for message of type '<CameraSweepResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string image_path      # The filesystem location of the captured images~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CameraSweepResult)))
  "Returns full string definition for message of type 'CameraSweepResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string image_path      # The filesystem location of the captured images~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CameraSweepResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'image_path))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CameraSweepResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CameraSweepResult
    (cl:cons ':image_path (image_path msg))
))
