; Auto-generated. Do not edit!


(cl:in-package com2009_msgs-msg)


;//! \htmlinclude CameraSweepGoal.msg.html

(cl:defclass <CameraSweepGoal> (roslisp-msg-protocol:ros-message)
  ((sweep_angle
    :reader sweep_angle
    :initarg :sweep_angle
    :type cl:float
    :initform 0.0)
   (image_count
    :reader image_count
    :initarg :image_count
    :type cl:integer
    :initform 0))
)

(cl:defclass CameraSweepGoal (<CameraSweepGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CameraSweepGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CameraSweepGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name com2009_msgs-msg:<CameraSweepGoal> is deprecated: use com2009_msgs-msg:CameraSweepGoal instead.")))

(cl:ensure-generic-function 'sweep_angle-val :lambda-list '(m))
(cl:defmethod sweep_angle-val ((m <CameraSweepGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader com2009_msgs-msg:sweep_angle-val is deprecated.  Use com2009_msgs-msg:sweep_angle instead.")
  (sweep_angle m))

(cl:ensure-generic-function 'image_count-val :lambda-list '(m))
(cl:defmethod image_count-val ((m <CameraSweepGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader com2009_msgs-msg:image_count-val is deprecated.  Use com2009_msgs-msg:image_count instead.")
  (image_count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CameraSweepGoal>) ostream)
  "Serializes a message object of type '<CameraSweepGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'sweep_angle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let* ((signed (cl:slot-value msg 'image_count)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CameraSweepGoal>) istream)
  "Deserializes a message object of type '<CameraSweepGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'sweep_angle) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'image_count) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CameraSweepGoal>)))
  "Returns string type for a message object of type '<CameraSweepGoal>"
  "com2009_msgs/CameraSweepGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CameraSweepGoal)))
  "Returns string type for a message object of type 'CameraSweepGoal"
  "com2009_msgs/CameraSweepGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CameraSweepGoal>)))
  "Returns md5sum for a message object of type '<CameraSweepGoal>"
  "b2278ec999c3591670076a420ec95a89")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CameraSweepGoal)))
  "Returns md5sum for a message object of type 'CameraSweepGoal"
  "b2278ec999c3591670076a420ec95a89")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CameraSweepGoal>)))
  "Returns full string definition for message of type '<CameraSweepGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float32 sweep_angle    # the angular sweep over which to capture images (degrees)~%int32 image_count      # the number of images to capture during the sweep~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CameraSweepGoal)))
  "Returns full string definition for message of type 'CameraSweepGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float32 sweep_angle    # the angular sweep over which to capture images (degrees)~%int32 image_count      # the number of images to capture during the sweep~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CameraSweepGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CameraSweepGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CameraSweepGoal
    (cl:cons ':sweep_angle (sweep_angle msg))
    (cl:cons ':image_count (image_count msg))
))
