; Auto-generated. Do not edit!


(cl:in-package com2009_msgs-msg)


;//! \htmlinclude CameraSweepFeedback.msg.html

(cl:defclass <CameraSweepFeedback> (roslisp-msg-protocol:ros-message)
  ((current_image
    :reader current_image
    :initarg :current_image
    :type cl:integer
    :initform 0)
   (current_angle
    :reader current_angle
    :initarg :current_angle
    :type cl:float
    :initform 0.0))
)

(cl:defclass CameraSweepFeedback (<CameraSweepFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CameraSweepFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CameraSweepFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name com2009_msgs-msg:<CameraSweepFeedback> is deprecated: use com2009_msgs-msg:CameraSweepFeedback instead.")))

(cl:ensure-generic-function 'current_image-val :lambda-list '(m))
(cl:defmethod current_image-val ((m <CameraSweepFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader com2009_msgs-msg:current_image-val is deprecated.  Use com2009_msgs-msg:current_image instead.")
  (current_image m))

(cl:ensure-generic-function 'current_angle-val :lambda-list '(m))
(cl:defmethod current_angle-val ((m <CameraSweepFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader com2009_msgs-msg:current_angle-val is deprecated.  Use com2009_msgs-msg:current_angle instead.")
  (current_angle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CameraSweepFeedback>) ostream)
  "Serializes a message object of type '<CameraSweepFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_image)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_angle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CameraSweepFeedback>) istream)
  "Deserializes a message object of type '<CameraSweepFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_image) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_angle) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CameraSweepFeedback>)))
  "Returns string type for a message object of type '<CameraSweepFeedback>"
  "com2009_msgs/CameraSweepFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CameraSweepFeedback)))
  "Returns string type for a message object of type 'CameraSweepFeedback"
  "com2009_msgs/CameraSweepFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CameraSweepFeedback>)))
  "Returns md5sum for a message object of type '<CameraSweepFeedback>"
  "ce6d21c3875dbd1341c6ddb7fafc46f4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CameraSweepFeedback)))
  "Returns md5sum for a message object of type 'CameraSweepFeedback"
  "ce6d21c3875dbd1341c6ddb7fafc46f4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CameraSweepFeedback>)))
  "Returns full string definition for message of type '<CameraSweepFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 current_image    # the number of images taken~%float32 current_angle  # the current angular position of the robot (degrees)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CameraSweepFeedback)))
  "Returns full string definition for message of type 'CameraSweepFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 current_image    # the number of images taken~%float32 current_angle  # the current angular position of the robot (degrees)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CameraSweepFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CameraSweepFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CameraSweepFeedback
    (cl:cons ':current_image (current_image msg))
    (cl:cons ':current_angle (current_angle msg))
))
