; Auto-generated. Do not edit!


(cl:in-package com2009_msgs-msg)


;//! \htmlinclude SearchGoal.msg.html

(cl:defclass <SearchGoal> (roslisp-msg-protocol:ros-message)
  ((fwd_velocity
    :reader fwd_velocity
    :initarg :fwd_velocity
    :type cl:float
    :initform 0.0)
   (approach_distance
    :reader approach_distance
    :initarg :approach_distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass SearchGoal (<SearchGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SearchGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SearchGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name com2009_msgs-msg:<SearchGoal> is deprecated: use com2009_msgs-msg:SearchGoal instead.")))

(cl:ensure-generic-function 'fwd_velocity-val :lambda-list '(m))
(cl:defmethod fwd_velocity-val ((m <SearchGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader com2009_msgs-msg:fwd_velocity-val is deprecated.  Use com2009_msgs-msg:fwd_velocity instead.")
  (fwd_velocity m))

(cl:ensure-generic-function 'approach_distance-val :lambda-list '(m))
(cl:defmethod approach_distance-val ((m <SearchGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader com2009_msgs-msg:approach_distance-val is deprecated.  Use com2009_msgs-msg:approach_distance instead.")
  (approach_distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SearchGoal>) ostream)
  "Serializes a message object of type '<SearchGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'fwd_velocity))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'approach_distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SearchGoal>) istream)
  "Deserializes a message object of type '<SearchGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'fwd_velocity) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'approach_distance) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SearchGoal>)))
  "Returns string type for a message object of type '<SearchGoal>"
  "com2009_msgs/SearchGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SearchGoal)))
  "Returns string type for a message object of type 'SearchGoal"
  "com2009_msgs/SearchGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SearchGoal>)))
  "Returns md5sum for a message object of type '<SearchGoal>"
  "375e5634624feebdedb76dd02a851d2c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SearchGoal)))
  "Returns md5sum for a message object of type 'SearchGoal"
  "375e5634624feebdedb76dd02a851d2c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SearchGoal>)))
  "Returns full string definition for message of type '<SearchGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float32 fwd_velocity               # The speed at which the robot should move forwards (m/s)~%float32 approach_distance          # LaserScan distance to trigger the robot to stop (meters) ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SearchGoal)))
  "Returns full string definition for message of type 'SearchGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float32 fwd_velocity               # The speed at which the robot should move forwards (m/s)~%float32 approach_distance          # LaserScan distance to trigger the robot to stop (meters) ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SearchGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SearchGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SearchGoal
    (cl:cons ':fwd_velocity (fwd_velocity msg))
    (cl:cons ':approach_distance (approach_distance msg))
))
