; Auto-generated. Do not edit!


(cl:in-package com2009_msgs-msg)


;//! \htmlinclude SearchFeedback.msg.html

(cl:defclass <SearchFeedback> (roslisp-msg-protocol:ros-message)
  ((current_distance_travelled
    :reader current_distance_travelled
    :initarg :current_distance_travelled
    :type cl:float
    :initform 0.0))
)

(cl:defclass SearchFeedback (<SearchFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SearchFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SearchFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name com2009_msgs-msg:<SearchFeedback> is deprecated: use com2009_msgs-msg:SearchFeedback instead.")))

(cl:ensure-generic-function 'current_distance_travelled-val :lambda-list '(m))
(cl:defmethod current_distance_travelled-val ((m <SearchFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader com2009_msgs-msg:current_distance_travelled-val is deprecated.  Use com2009_msgs-msg:current_distance_travelled instead.")
  (current_distance_travelled m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SearchFeedback>) ostream)
  "Serializes a message object of type '<SearchFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_distance_travelled))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SearchFeedback>) istream)
  "Deserializes a message object of type '<SearchFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_distance_travelled) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SearchFeedback>)))
  "Returns string type for a message object of type '<SearchFeedback>"
  "com2009_msgs/SearchFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SearchFeedback)))
  "Returns string type for a message object of type 'SearchFeedback"
  "com2009_msgs/SearchFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SearchFeedback>)))
  "Returns md5sum for a message object of type '<SearchFeedback>"
  "38da9e86e96ffd60957129b259df2656")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SearchFeedback)))
  "Returns md5sum for a message object of type 'SearchFeedback"
  "38da9e86e96ffd60957129b259df2656")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SearchFeedback>)))
  "Returns full string definition for message of type '<SearchFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 current_distance_travelled # Distance travelled so far during the action (meters)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SearchFeedback)))
  "Returns full string definition for message of type 'SearchFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 current_distance_travelled # Distance travelled so far during the action (meters)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SearchFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SearchFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SearchFeedback
    (cl:cons ':current_distance_travelled (current_distance_travelled msg))
))
