(cl:defpackage com2009_msgs-srv
  (:use )
  (:export
   "APPROACH"
   "<APPROACH-REQUEST>"
   "APPROACH-REQUEST"
   "<APPROACH-RESPONSE>"
   "APPROACH-RESPONSE"
   "SETBOOL"
   "<SETBOOL-REQUEST>"
   "SETBOOL-REQUEST"
   "<SETBOOL-RESPONSE>"
   "SETBOOL-RESPONSE"
   "TIMEDMOVEMENT"
   "<TIMEDMOVEMENT-REQUEST>"
   "TIMEDMOVEMENT-REQUEST"
   "<TIMEDMOVEMENT-RESPONSE>"
   "TIMEDMOVEMENT-RESPONSE"
  ))

