// Generated by gencpp from file com2009_msgs/ApproachResponse.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_APPROACHRESPONSE_H
#define COM2009_MSGS_MESSAGE_APPROACHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com2009_msgs
{
template <class ContainerAllocator>
struct ApproachResponse_
{
  typedef ApproachResponse_<ContainerAllocator> Type;

  ApproachResponse_()
    : response_message()  {
    }
  ApproachResponse_(const ContainerAllocator& _alloc)
    : response_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_message_type;
  _response_message_type response_message;





  typedef boost::shared_ptr< ::com2009_msgs::ApproachResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com2009_msgs::ApproachResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ApproachResponse_

typedef ::com2009_msgs::ApproachResponse_<std::allocator<void> > ApproachResponse;

typedef boost::shared_ptr< ::com2009_msgs::ApproachResponse > ApproachResponsePtr;
typedef boost::shared_ptr< ::com2009_msgs::ApproachResponse const> ApproachResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com2009_msgs::ApproachResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com2009_msgs::ApproachResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com2009_msgs::ApproachResponse_<ContainerAllocator1> & lhs, const ::com2009_msgs::ApproachResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response_message == rhs.response_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com2009_msgs::ApproachResponse_<ContainerAllocator1> & lhs, const ::com2009_msgs::ApproachResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com2009_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::ApproachResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::ApproachResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::ApproachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::ApproachResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::ApproachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::ApproachResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com2009_msgs::ApproachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b45950c35bda99bcc3b6c93c7abc007";
  }

  static const char* value(const ::com2009_msgs::ApproachResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b45950c35bda99bULL;
  static const uint64_t static_value2 = 0xcc3b6c93c7abc007ULL;
};

template<class ContainerAllocator>
struct DataType< ::com2009_msgs::ApproachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com2009_msgs/ApproachResponse";
  }

  static const char* value(const ::com2009_msgs::ApproachResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com2009_msgs::ApproachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response_message\n"
"\n"
;
  }

  static const char* value(const ::com2009_msgs::ApproachResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com2009_msgs::ApproachResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ApproachResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com2009_msgs::ApproachResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com2009_msgs::ApproachResponse_<ContainerAllocator>& v)
  {
    s << indent << "response_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_APPROACHRESPONSE_H
