// Generated by gencpp from file com2009_msgs/Approach.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_APPROACH_H
#define COM2009_MSGS_MESSAGE_APPROACH_H

#include <ros/service_traits.h>


#include <com2009_msgs/ApproachRequest.h>
#include <com2009_msgs/ApproachResponse.h>


namespace com2009_msgs
{

struct Approach
{

typedef ApproachRequest Request;
typedef ApproachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Approach
} // namespace com2009_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::com2009_msgs::Approach > {
  static const char* value()
  {
    return "9969ab457f53a37a2d75e40a76a1f887";
  }

  static const char* value(const ::com2009_msgs::Approach&) { return value(); }
};

template<>
struct DataType< ::com2009_msgs::Approach > {
  static const char* value()
  {
    return "com2009_msgs/Approach";
  }

  static const char* value(const ::com2009_msgs::Approach&) { return value(); }
};


// service_traits::MD5Sum< ::com2009_msgs::ApproachRequest> should match
// service_traits::MD5Sum< ::com2009_msgs::Approach >
template<>
struct MD5Sum< ::com2009_msgs::ApproachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::com2009_msgs::Approach >::value();
  }
  static const char* value(const ::com2009_msgs::ApproachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::com2009_msgs::ApproachRequest> should match
// service_traits::DataType< ::com2009_msgs::Approach >
template<>
struct DataType< ::com2009_msgs::ApproachRequest>
{
  static const char* value()
  {
    return DataType< ::com2009_msgs::Approach >::value();
  }
  static const char* value(const ::com2009_msgs::ApproachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::com2009_msgs::ApproachResponse> should match
// service_traits::MD5Sum< ::com2009_msgs::Approach >
template<>
struct MD5Sum< ::com2009_msgs::ApproachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::com2009_msgs::Approach >::value();
  }
  static const char* value(const ::com2009_msgs::ApproachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::com2009_msgs::ApproachResponse> should match
// service_traits::DataType< ::com2009_msgs::Approach >
template<>
struct DataType< ::com2009_msgs::ApproachResponse>
{
  static const char* value()
  {
    return DataType< ::com2009_msgs::Approach >::value();
  }
  static const char* value(const ::com2009_msgs::ApproachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_APPROACH_H
