// Generated by gencpp from file com2009_msgs/CameraSweepResult.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_CAMERASWEEPRESULT_H
#define COM2009_MSGS_MESSAGE_CAMERASWEEPRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com2009_msgs
{
template <class ContainerAllocator>
struct CameraSweepResult_
{
  typedef CameraSweepResult_<ContainerAllocator> Type;

  CameraSweepResult_()
    : image_path()  {
    }
  CameraSweepResult_(const ContainerAllocator& _alloc)
    : image_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _image_path_type;
  _image_path_type image_path;





  typedef boost::shared_ptr< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> const> ConstPtr;

}; // struct CameraSweepResult_

typedef ::com2009_msgs::CameraSweepResult_<std::allocator<void> > CameraSweepResult;

typedef boost::shared_ptr< ::com2009_msgs::CameraSweepResult > CameraSweepResultPtr;
typedef boost::shared_ptr< ::com2009_msgs::CameraSweepResult const> CameraSweepResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com2009_msgs::CameraSweepResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com2009_msgs::CameraSweepResult_<ContainerAllocator1> & lhs, const ::com2009_msgs::CameraSweepResult_<ContainerAllocator2> & rhs)
{
  return lhs.image_path == rhs.image_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com2009_msgs::CameraSweepResult_<ContainerAllocator1> & lhs, const ::com2009_msgs::CameraSweepResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com2009_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65568c775bfbc96c6265c3d13d7e1a07";
  }

  static const char* value(const ::com2009_msgs::CameraSweepResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65568c775bfbc96cULL;
  static const uint64_t static_value2 = 0x6265c3d13d7e1a07ULL;
};

template<class ContainerAllocator>
struct DataType< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com2009_msgs/CameraSweepResult";
  }

  static const char* value(const ::com2009_msgs::CameraSweepResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"string image_path      # The filesystem location of the captured images\n"
;
  }

  static const char* value(const ::com2009_msgs::CameraSweepResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraSweepResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com2009_msgs::CameraSweepResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com2009_msgs::CameraSweepResult_<ContainerAllocator>& v)
  {
    s << indent << "image_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_CAMERASWEEPRESULT_H
