// Generated by gencpp from file com2009_msgs/CameraSweepFeedback.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_CAMERASWEEPFEEDBACK_H
#define COM2009_MSGS_MESSAGE_CAMERASWEEPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com2009_msgs
{
template <class ContainerAllocator>
struct CameraSweepFeedback_
{
  typedef CameraSweepFeedback_<ContainerAllocator> Type;

  CameraSweepFeedback_()
    : current_image(0)
    , current_angle(0.0)  {
    }
  CameraSweepFeedback_(const ContainerAllocator& _alloc)
    : current_image(0)
    , current_angle(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _current_image_type;
  _current_image_type current_image;

   typedef float _current_angle_type;
  _current_angle_type current_angle;





  typedef boost::shared_ptr< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CameraSweepFeedback_

typedef ::com2009_msgs::CameraSweepFeedback_<std::allocator<void> > CameraSweepFeedback;

typedef boost::shared_ptr< ::com2009_msgs::CameraSweepFeedback > CameraSweepFeedbackPtr;
typedef boost::shared_ptr< ::com2009_msgs::CameraSweepFeedback const> CameraSweepFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator1> & lhs, const ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_image == rhs.current_image &&
    lhs.current_angle == rhs.current_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator1> & lhs, const ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com2009_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce6d21c3875dbd1341c6ddb7fafc46f4";
  }

  static const char* value(const ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce6d21c3875dbd13ULL;
  static const uint64_t static_value2 = 0x41c6ddb7fafc46f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com2009_msgs/CameraSweepFeedback";
  }

  static const char* value(const ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32 current_image    # the number of images taken\n"
"float32 current_angle  # the current angular position of the robot (degrees)\n"
"\n"
;
  }

  static const char* value(const ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_image);
      stream.next(m.current_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraSweepFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com2009_msgs::CameraSweepFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_image: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_image);
    s << indent << "current_angle: ";
    Printer<float>::stream(s, indent + "  ", v.current_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_CAMERASWEEPFEEDBACK_H
