// Generated by gencpp from file com2009_msgs/NumpyFloat32Array.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_NUMPYFLOAT32ARRAY_H
#define COM2009_MSGS_MESSAGE_NUMPYFLOAT32ARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com2009_msgs
{
template <class ContainerAllocator>
struct NumpyFloat32Array_
{
  typedef NumpyFloat32Array_<ContainerAllocator> Type;

  NumpyFloat32Array_()
    : data()  {
    }
  NumpyFloat32Array_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> const> ConstPtr;

}; // struct NumpyFloat32Array_

typedef ::com2009_msgs::NumpyFloat32Array_<std::allocator<void> > NumpyFloat32Array;

typedef boost::shared_ptr< ::com2009_msgs::NumpyFloat32Array > NumpyFloat32ArrayPtr;
typedef boost::shared_ptr< ::com2009_msgs::NumpyFloat32Array const> NumpyFloat32ArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator1> & lhs, const ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator1> & lhs, const ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com2009_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com2009_msgs/NumpyFloat32Array";
  }

  static const char* value(const ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n"
;
  }

  static const char* value(const ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NumpyFloat32Array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com2009_msgs::NumpyFloat32Array_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_NUMPYFLOAT32ARRAY_H
