// Generated by gencpp from file com2009_msgs/SearchGoal.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_SEARCHGOAL_H
#define COM2009_MSGS_MESSAGE_SEARCHGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com2009_msgs
{
template <class ContainerAllocator>
struct SearchGoal_
{
  typedef SearchGoal_<ContainerAllocator> Type;

  SearchGoal_()
    : fwd_velocity(0.0)
    , approach_distance(0.0)  {
    }
  SearchGoal_(const ContainerAllocator& _alloc)
    : fwd_velocity(0.0)
    , approach_distance(0.0)  {
  (void)_alloc;
    }



   typedef float _fwd_velocity_type;
  _fwd_velocity_type fwd_velocity;

   typedef float _approach_distance_type;
  _approach_distance_type approach_distance;





  typedef boost::shared_ptr< ::com2009_msgs::SearchGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com2009_msgs::SearchGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SearchGoal_

typedef ::com2009_msgs::SearchGoal_<std::allocator<void> > SearchGoal;

typedef boost::shared_ptr< ::com2009_msgs::SearchGoal > SearchGoalPtr;
typedef boost::shared_ptr< ::com2009_msgs::SearchGoal const> SearchGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com2009_msgs::SearchGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com2009_msgs::SearchGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com2009_msgs::SearchGoal_<ContainerAllocator1> & lhs, const ::com2009_msgs::SearchGoal_<ContainerAllocator2> & rhs)
{
  return lhs.fwd_velocity == rhs.fwd_velocity &&
    lhs.approach_distance == rhs.approach_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com2009_msgs::SearchGoal_<ContainerAllocator1> & lhs, const ::com2009_msgs::SearchGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com2009_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::SearchGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::SearchGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::SearchGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::SearchGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::SearchGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::SearchGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com2009_msgs::SearchGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "375e5634624feebdedb76dd02a851d2c";
  }

  static const char* value(const ::com2009_msgs::SearchGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x375e5634624feebdULL;
  static const uint64_t static_value2 = 0xedb76dd02a851d2cULL;
};

template<class ContainerAllocator>
struct DataType< ::com2009_msgs::SearchGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com2009_msgs/SearchGoal";
  }

  static const char* value(const ::com2009_msgs::SearchGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com2009_msgs::SearchGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"float32 fwd_velocity               # The speed at which the robot should move forwards (m/s)\n"
"float32 approach_distance          # LaserScan distance to trigger the robot to stop (meters) \n"
;
  }

  static const char* value(const ::com2009_msgs::SearchGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com2009_msgs::SearchGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fwd_velocity);
      stream.next(m.approach_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SearchGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com2009_msgs::SearchGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com2009_msgs::SearchGoal_<ContainerAllocator>& v)
  {
    s << indent << "fwd_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.fwd_velocity);
    s << indent << "approach_distance: ";
    Printer<float>::stream(s, indent + "  ", v.approach_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_SEARCHGOAL_H
