// Generated by gencpp from file com2009_msgs/SearchFeedback.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_SEARCHFEEDBACK_H
#define COM2009_MSGS_MESSAGE_SEARCHFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com2009_msgs
{
template <class ContainerAllocator>
struct SearchFeedback_
{
  typedef SearchFeedback_<ContainerAllocator> Type;

  SearchFeedback_()
    : current_distance_travelled(0.0)  {
    }
  SearchFeedback_(const ContainerAllocator& _alloc)
    : current_distance_travelled(0.0)  {
  (void)_alloc;
    }



   typedef float _current_distance_travelled_type;
  _current_distance_travelled_type current_distance_travelled;





  typedef boost::shared_ptr< ::com2009_msgs::SearchFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com2009_msgs::SearchFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SearchFeedback_

typedef ::com2009_msgs::SearchFeedback_<std::allocator<void> > SearchFeedback;

typedef boost::shared_ptr< ::com2009_msgs::SearchFeedback > SearchFeedbackPtr;
typedef boost::shared_ptr< ::com2009_msgs::SearchFeedback const> SearchFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com2009_msgs::SearchFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com2009_msgs::SearchFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com2009_msgs::SearchFeedback_<ContainerAllocator1> & lhs, const ::com2009_msgs::SearchFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_distance_travelled == rhs.current_distance_travelled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com2009_msgs::SearchFeedback_<ContainerAllocator1> & lhs, const ::com2009_msgs::SearchFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com2009_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::SearchFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::SearchFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::SearchFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::SearchFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::SearchFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::SearchFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com2009_msgs::SearchFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38da9e86e96ffd60957129b259df2656";
  }

  static const char* value(const ::com2009_msgs::SearchFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38da9e86e96ffd60ULL;
  static const uint64_t static_value2 = 0x957129b259df2656ULL;
};

template<class ContainerAllocator>
struct DataType< ::com2009_msgs::SearchFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com2009_msgs/SearchFeedback";
  }

  static const char* value(const ::com2009_msgs::SearchFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com2009_msgs::SearchFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 current_distance_travelled # Distance travelled so far during the action (meters)\n"
"\n"
;
  }

  static const char* value(const ::com2009_msgs::SearchFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com2009_msgs::SearchFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_distance_travelled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SearchFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com2009_msgs::SearchFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com2009_msgs::SearchFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_distance_travelled: ";
    Printer<float>::stream(s, indent + "  ", v.current_distance_travelled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_SEARCHFEEDBACK_H
