// Generated by gencpp from file com2009_msgs/SetBool.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_SETBOOL_H
#define COM2009_MSGS_MESSAGE_SETBOOL_H

#include <ros/service_traits.h>


#include <com2009_msgs/SetBoolRequest.h>
#include <com2009_msgs/SetBoolResponse.h>


namespace com2009_msgs
{

struct SetBool
{

typedef SetBoolRequest Request;
typedef SetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBool
} // namespace com2009_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::com2009_msgs::SetBool > {
  static const char* value()
  {
    return "809e515273297bb2c71988526658bce7";
  }

  static const char* value(const ::com2009_msgs::SetBool&) { return value(); }
};

template<>
struct DataType< ::com2009_msgs::SetBool > {
  static const char* value()
  {
    return "com2009_msgs/SetBool";
  }

  static const char* value(const ::com2009_msgs::SetBool&) { return value(); }
};


// service_traits::MD5Sum< ::com2009_msgs::SetBoolRequest> should match
// service_traits::MD5Sum< ::com2009_msgs::SetBool >
template<>
struct MD5Sum< ::com2009_msgs::SetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::com2009_msgs::SetBool >::value();
  }
  static const char* value(const ::com2009_msgs::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::com2009_msgs::SetBoolRequest> should match
// service_traits::DataType< ::com2009_msgs::SetBool >
template<>
struct DataType< ::com2009_msgs::SetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::com2009_msgs::SetBool >::value();
  }
  static const char* value(const ::com2009_msgs::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::com2009_msgs::SetBoolResponse> should match
// service_traits::MD5Sum< ::com2009_msgs::SetBool >
template<>
struct MD5Sum< ::com2009_msgs::SetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::com2009_msgs::SetBool >::value();
  }
  static const char* value(const ::com2009_msgs::SetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::com2009_msgs::SetBoolResponse> should match
// service_traits::DataType< ::com2009_msgs::SetBool >
template<>
struct DataType< ::com2009_msgs::SetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::com2009_msgs::SetBool >::value();
  }
  static const char* value(const ::com2009_msgs::SetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_SETBOOL_H
