// Generated by gencpp from file com2009_msgs/SetBoolResponse.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_SETBOOLRESPONSE_H
#define COM2009_MSGS_MESSAGE_SETBOOLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com2009_msgs
{
template <class ContainerAllocator>
struct SetBoolResponse_
{
  typedef SetBoolResponse_<ContainerAllocator> Type;

  SetBoolResponse_()
    : response_signal(false)
    , response_message()  {
    }
  SetBoolResponse_(const ContainerAllocator& _alloc)
    : response_signal(false)
    , response_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _response_signal_type;
  _response_signal_type response_signal;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_message_type;
  _response_message_type response_message;





  typedef boost::shared_ptr< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetBoolResponse_

typedef ::com2009_msgs::SetBoolResponse_<std::allocator<void> > SetBoolResponse;

typedef boost::shared_ptr< ::com2009_msgs::SetBoolResponse > SetBoolResponsePtr;
typedef boost::shared_ptr< ::com2009_msgs::SetBoolResponse const> SetBoolResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com2009_msgs::SetBoolResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com2009_msgs::SetBoolResponse_<ContainerAllocator1> & lhs, const ::com2009_msgs::SetBoolResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response_signal == rhs.response_signal &&
    lhs.response_message == rhs.response_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com2009_msgs::SetBoolResponse_<ContainerAllocator1> & lhs, const ::com2009_msgs::SetBoolResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com2009_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2eebae83968108296ba3643d655e624e";
  }

  static const char* value(const ::com2009_msgs::SetBoolResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2eebae8396810829ULL;
  static const uint64_t static_value2 = 0x6ba3643d655e624eULL;
};

template<class ContainerAllocator>
struct DataType< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com2009_msgs/SetBoolResponse";
  }

  static const char* value(const ::com2009_msgs::SetBoolResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response_signal      # A boolean response to indicate that the action has been performed\n"
"string response_message   # A message to provide further information to the service caller\n"
"\n"
;
  }

  static const char* value(const ::com2009_msgs::SetBoolResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response_signal);
      stream.next(m.response_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBoolResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com2009_msgs::SetBoolResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com2009_msgs::SetBoolResponse_<ContainerAllocator>& v)
  {
    s << indent << "response_signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response_signal);
    s << indent << "response_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_SETBOOLRESPONSE_H
