// Generated by gencpp from file com2009_msgs/TimedMovement.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_TIMEDMOVEMENT_H
#define COM2009_MSGS_MESSAGE_TIMEDMOVEMENT_H

#include <ros/service_traits.h>


#include <com2009_msgs/TimedMovementRequest.h>
#include <com2009_msgs/TimedMovementResponse.h>


namespace com2009_msgs
{

struct TimedMovement
{

typedef TimedMovementRequest Request;
typedef TimedMovementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TimedMovement
} // namespace com2009_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::com2009_msgs::TimedMovement > {
  static const char* value()
  {
    return "01da3949d1975f89601d90342172dc85";
  }

  static const char* value(const ::com2009_msgs::TimedMovement&) { return value(); }
};

template<>
struct DataType< ::com2009_msgs::TimedMovement > {
  static const char* value()
  {
    return "com2009_msgs/TimedMovement";
  }

  static const char* value(const ::com2009_msgs::TimedMovement&) { return value(); }
};


// service_traits::MD5Sum< ::com2009_msgs::TimedMovementRequest> should match
// service_traits::MD5Sum< ::com2009_msgs::TimedMovement >
template<>
struct MD5Sum< ::com2009_msgs::TimedMovementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::com2009_msgs::TimedMovement >::value();
  }
  static const char* value(const ::com2009_msgs::TimedMovementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::com2009_msgs::TimedMovementRequest> should match
// service_traits::DataType< ::com2009_msgs::TimedMovement >
template<>
struct DataType< ::com2009_msgs::TimedMovementRequest>
{
  static const char* value()
  {
    return DataType< ::com2009_msgs::TimedMovement >::value();
  }
  static const char* value(const ::com2009_msgs::TimedMovementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::com2009_msgs::TimedMovementResponse> should match
// service_traits::MD5Sum< ::com2009_msgs::TimedMovement >
template<>
struct MD5Sum< ::com2009_msgs::TimedMovementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::com2009_msgs::TimedMovement >::value();
  }
  static const char* value(const ::com2009_msgs::TimedMovementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::com2009_msgs::TimedMovementResponse> should match
// service_traits::DataType< ::com2009_msgs::TimedMovement >
template<>
struct DataType< ::com2009_msgs::TimedMovementResponse>
{
  static const char* value()
  {
    return DataType< ::com2009_msgs::TimedMovement >::value();
  }
  static const char* value(const ::com2009_msgs::TimedMovementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_TIMEDMOVEMENT_H
