// Generated by gencpp from file com2009_msgs/TimedMovementRequest.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_TIMEDMOVEMENTREQUEST_H
#define COM2009_MSGS_MESSAGE_TIMEDMOVEMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com2009_msgs
{
template <class ContainerAllocator>
struct TimedMovementRequest_
{
  typedef TimedMovementRequest_<ContainerAllocator> Type;

  TimedMovementRequest_()
    : movement_request()
    , duration(0)  {
    }
  TimedMovementRequest_(const ContainerAllocator& _alloc)
    : movement_request(_alloc)
    , duration(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _movement_request_type;
  _movement_request_type movement_request;

   typedef int32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TimedMovementRequest_

typedef ::com2009_msgs::TimedMovementRequest_<std::allocator<void> > TimedMovementRequest;

typedef boost::shared_ptr< ::com2009_msgs::TimedMovementRequest > TimedMovementRequestPtr;
typedef boost::shared_ptr< ::com2009_msgs::TimedMovementRequest const> TimedMovementRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com2009_msgs::TimedMovementRequest_<ContainerAllocator1> & lhs, const ::com2009_msgs::TimedMovementRequest_<ContainerAllocator2> & rhs)
{
  return lhs.movement_request == rhs.movement_request &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com2009_msgs::TimedMovementRequest_<ContainerAllocator1> & lhs, const ::com2009_msgs::TimedMovementRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com2009_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98ec7782393184833d09a76461890b3f";
  }

  static const char* value(const ::com2009_msgs::TimedMovementRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98ec778239318483ULL;
  static const uint64_t static_value2 = 0x3d09a76461890b3fULL;
};

template<class ContainerAllocator>
struct DataType< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com2009_msgs/TimedMovementRequest";
  }

  static const char* value(const ::com2009_msgs::TimedMovementRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string movement_request  # the type of movement to perform\n"
"int32 duration           # the time (in seconds) to perform the movement for\n"
;
  }

  static const char* value(const ::com2009_msgs::TimedMovementRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.movement_request);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimedMovementRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com2009_msgs::TimedMovementRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com2009_msgs::TimedMovementRequest_<ContainerAllocator>& v)
  {
    s << indent << "movement_request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.movement_request);
    s << indent << "duration: ";
    Printer<int32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_TIMEDMOVEMENTREQUEST_H
