// Generated by gencpp from file com2009_msgs/TimedMovementResponse.msg
// DO NOT EDIT!


#ifndef COM2009_MSGS_MESSAGE_TIMEDMOVEMENTRESPONSE_H
#define COM2009_MSGS_MESSAGE_TIMEDMOVEMENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com2009_msgs
{
template <class ContainerAllocator>
struct TimedMovementResponse_
{
  typedef TimedMovementResponse_<ContainerAllocator> Type;

  TimedMovementResponse_()
    : success(false)  {
    }
  TimedMovementResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TimedMovementResponse_

typedef ::com2009_msgs::TimedMovementResponse_<std::allocator<void> > TimedMovementResponse;

typedef boost::shared_ptr< ::com2009_msgs::TimedMovementResponse > TimedMovementResponsePtr;
typedef boost::shared_ptr< ::com2009_msgs::TimedMovementResponse const> TimedMovementResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::com2009_msgs::TimedMovementResponse_<ContainerAllocator1> & lhs, const ::com2009_msgs::TimedMovementResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::com2009_msgs::TimedMovementResponse_<ContainerAllocator1> & lhs, const ::com2009_msgs::TimedMovementResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace com2009_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::com2009_msgs::TimedMovementResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com2009_msgs/TimedMovementResponse";
  }

  static const char* value(const ::com2009_msgs::TimedMovementResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success             # a boolean response to indicate that the service has completed\n"
"\n"
;
  }

  static const char* value(const ::com2009_msgs::TimedMovementResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimedMovementResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com2009_msgs::TimedMovementResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com2009_msgs::TimedMovementResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM2009_MSGS_MESSAGE_TIMEDMOVEMENTRESPONSE_H
