// Auto-generated. Do not edit!

// (in-package com2009_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CameraSweepFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_image = null;
      this.current_angle = null;
    }
    else {
      if (initObj.hasOwnProperty('current_image')) {
        this.current_image = initObj.current_image
      }
      else {
        this.current_image = 0;
      }
      if (initObj.hasOwnProperty('current_angle')) {
        this.current_angle = initObj.current_angle
      }
      else {
        this.current_angle = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CameraSweepFeedback
    // Serialize message field [current_image]
    bufferOffset = _serializer.int32(obj.current_image, buffer, bufferOffset);
    // Serialize message field [current_angle]
    bufferOffset = _serializer.float32(obj.current_angle, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CameraSweepFeedback
    let len;
    let data = new CameraSweepFeedback(null);
    // Deserialize message field [current_image]
    data.current_image = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [current_angle]
    data.current_angle = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'com2009_msgs/CameraSweepFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ce6d21c3875dbd1341c6ddb7fafc46f4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32 current_image    # the number of images taken
    float32 current_angle  # the current angular position of the robot (degrees)
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CameraSweepFeedback(null);
    if (msg.current_image !== undefined) {
      resolved.current_image = msg.current_image;
    }
    else {
      resolved.current_image = 0
    }

    if (msg.current_angle !== undefined) {
      resolved.current_angle = msg.current_angle;
    }
    else {
      resolved.current_angle = 0.0
    }

    return resolved;
    }
};

module.exports = CameraSweepFeedback;
