// Auto-generated. Do not edit!

// (in-package com2009_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SearchFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_distance_travelled = null;
    }
    else {
      if (initObj.hasOwnProperty('current_distance_travelled')) {
        this.current_distance_travelled = initObj.current_distance_travelled
      }
      else {
        this.current_distance_travelled = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SearchFeedback
    // Serialize message field [current_distance_travelled]
    bufferOffset = _serializer.float32(obj.current_distance_travelled, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SearchFeedback
    let len;
    let data = new SearchFeedback(null);
    // Deserialize message field [current_distance_travelled]
    data.current_distance_travelled = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'com2009_msgs/SearchFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '38da9e86e96ffd60957129b259df2656';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 current_distance_travelled # Distance travelled so far during the action (meters)
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SearchFeedback(null);
    if (msg.current_distance_travelled !== undefined) {
      resolved.current_distance_travelled = msg.current_distance_travelled;
    }
    else {
      resolved.current_distance_travelled = 0.0
    }

    return resolved;
    }
};

module.exports = SearchFeedback;
